In [1]:
import pandas as pd
import re

In [2]:
df = pd.read_excel("data/Chair-Cochair.xlsx", sheet_name="Chair-cochairs", skiprows=2)

In [3]:
df.head(3)

,Num,Symposia,Role,Thai,Name,Affiliation,Email,Ignore
0,1,"Semiconductors, Photonic Materials and Devices",Chair,รองศาสตราจารย์ ดร. อนุชา วัชระภาสร,Assoc. Prof. Dr. Anucha Watcharapasorn,Chiang Mai University,anucha.w@cmu.ac.th,NaN
1,1,"Semiconductors, Photonic Materials and Devices",Co-chair,ศาสตราจารย์ ดร. วิษณุ เพชรภา,Prof. Dr. Wisanu Pecharapa,King Mongkut's Institute of Technology Ladkrabang,wisanu.pe@kmitl.ac.th,NaN
2,1,"Semiconductors, Photonic Materials and Devices",Co-chair,ดร. ทศพร เลิศวณิชผล,Dr. Tossaporn Lertvanithphol,National Electronics and Computer Technology C...,tossaporn.ler@nectec.or.th,NaN

In [4]:
# Remove rows where "Ignore" is "YES"
filt = df["Ignore"] == "YES"
display(df[filt])
df = df[~filt]

,Num,Symposia,Role,Thai,Name,Affiliation,Email,Ignore
10,2,"Polymers, Biomaterials and Medical Devices",Co-chair,ดร. ศรภัทร นิยมสินธุ์,Dr. Sorapat Niyomsin,Chulalongkorn University,sorapat.n@chula.ac.th,YES

In [5]:
def extract_name(comb_txt):
    pattern = re.compile(r'^(?:Assoc\. Prof\. Dr\.|Asst\. Prof\. Dr\.|Prof\. Dr\.|Dr\.)\s+(.*)$')
    m = pattern.match(comb_txt.strip())
    if m:
        return m.group(1)
    return ""

df["name_strip"] = df["Name"].apply(extract_name)
df.head(3)

,Num,Symposia,Role,Thai,Name,Affiliation,Email,Ignore,name_strip
0,1,"Semiconductors, Photonic Materials and Devices",Chair,รองศาสตราจารย์ ดร. อนุชา วัชระภาสร,Assoc. Prof. Dr. Anucha Watcharapasorn,Chiang Mai University,anucha.w@cmu.ac.th,NaN,Anucha Watcharapasorn
1,1,"Semiconductors, Photonic Materials and Devices",Co-chair,ศาสตราจารย์ ดร. วิษณุ เพชรภา,Prof. Dr. Wisanu Pecharapa,King Mongkut's Institute of Technology Ladkrabang,wisanu.pe@kmitl.ac.th,NaN,Wisanu Pecharapa
2,1,"Semiconductors, Photonic Materials and Devices",Co-chair,ดร. ทศพร เลิศวณิชผล,Dr. Tossaporn Lertvanithphol,National Electronics and Computer Technology C...,tossaporn.ler@nectec.or.th,NaN,Tossaporn Lertvanithphol

In [6]:
def get_title(row):
    name = row["Name"]
    name_strip = row["name_strip"]
    title = name.replace(name_strip, "").strip()
    return title.strip()

df["title"] = df.apply(get_title, axis=1)
df.head(3)

,Num,Symposia,Role,Thai,Name,Affiliation,Email,Ignore,name_strip,title
0,1,"Semiconductors, Photonic Materials and Devices",Chair,รองศาสตราจารย์ ดร. อนุชา วัชระภาสร,Assoc. Prof. Dr. Anucha Watcharapasorn,Chiang Mai University,anucha.w@cmu.ac.th,NaN,Anucha Watcharapasorn,Assoc. Prof. Dr.
1,1,"Semiconductors, Photonic Materials and Devices",Co-chair,ศาสตราจารย์ ดร. วิษณุ เพชรภา,Prof. Dr. Wisanu Pecharapa,King Mongkut's Institute of Technology Ladkrabang,wisanu.pe@kmitl.ac.th,NaN,Wisanu Pecharapa,Prof. Dr.
2,1,"Semiconductors, Photonic Materials and Devices",Co-chair,ดร. ทศพร เลิศวณิชผล,Dr. Tossaporn Lertvanithphol,National Electronics and Computer Technology C...,tossaporn.ler@nectec.or.th,NaN,Tossaporn Lertvanithphol,Dr.

In [7]:
def create_filename(row):
    X = row["Num"]
    Role = row["Role"]
    Name = row["name_strip"]
    return f"Invitation IUMRS-ICEM2026_Symp{X}_{Role}_{Name}"

df["filename"] = df.apply(create_filename, axis=1)
df["filename"].values

<StringArray>
[         'Invitation IUMRS-ICEM2026_Symp1_Chair_Anucha Watcharapasorn',
            'Invitation IUMRS-ICEM2026_Symp1_Co-chair_Wisanu Pecharapa',
    'Invitation IUMRS-ICEM2026_Symp1_Co-chair_Tossaporn Lertvanithphol',
          'Invitation IUMRS-ICEM2026_Symp1_Co-chair_Doldet Tantraviwat',
       'Invitation IUMRS-ICEM2026_Symp1_Co-chair_Thutiyaporn Thiwawong',
                'Invitation IUMRS-ICEM2026_Symp2_Chair_Winita Punyodom',
            'Invitation IUMRS-ICEM2026_Symp2_Co-chair_Kannika Sahakaro',
                'Invitation IUMRS-ICEM2026_Symp2_Co-chair_Sukunya Ross',
           'Invitation IUMRS-ICEM2026_Symp2_Co-chair_Panya Sunintaboon',
    'Invitation IUMRS-ICEM2026_Symp2_Co-chair_Patchara Punyamoonwongsa',
            'Invitation IUMRS-ICEM2026_Symp3_Chair_Adisorn Tuantranont',
             'Invitation IUMRS-ICEM2026_Symp3_Co-chair_Chanpen Karuwan',
          'Invitation IUMRS-ICEM2026_Symp3_Co-chair_Kamonwad Ngamchuea',
            'Invitation IUMRS-ICEM2026_Symp4_Chair_Naratip Vittayakorn',
         'Invitation IUMRS-ICEM2026_Symp4_Co-chair_Theerachai Bongkarn',
    'Invitation IUMRS-ICEM2026_Symp4_Co-chair_Sasipohn Prasertpalichat',
         'Invitation IUMRS-ICEM2026_Symp4_Co-chair_Thitirat Charoonsuk',
          'Invitation IUMRS-ICEM2026_Symp4_Co-chair_Jessada Chureemart',
                'Invitation IUMRS-ICEM2026_Symp5_Chair_Vinich Promarak',
 'Invitation IUMRS-ICEM2026_Symp5_Co-chair_Duangmanee Wongratanaphisan',
  'Invitation IUMRS-ICEM2026_Symp5_Co-chair_Pichaya Pattanasattayavong',
           'Invitation IUMRS-ICEM2026_Symp5_Co-chair_Pisist Kumnorkeaw',
              'Invitation IUMRS-ICEM2026_Symp6_Chair_Pinit Kidkhunthod',
      'Invitation IUMRS-ICEM2026_Symp6_Co-chair_Siriporn Jungsuttiwong',
          'Invitation IUMRS-ICEM2026_Symp6_Co-chair_Soorathep Kheawhom',
         'Invitation IUMRS-ICEM2026_Symp6_Co-chair_Prasit Pattananuwat',
             'Invitation IUMRS-ICEM2026_Symp7_Chair_Anchalee Manonukul',
          'Invitation IUMRS-ICEM2026_Symp7_Co-chair_Oratai Jongprateep',
             'Invitation IUMRS-ICEM2026_Symp7_Co-chair_Niti Yongvanich',
           'Invitation IUMRS-ICEM2026_Symp8_Chair_Supree Pinitsoontorn',
                            'Invitation IUMRS-ICEM2026_Symp8_Co-chair_',
          'Invitation IUMRS-ICEM2026_Symp8_Co-chair_Yingyot Poo-Arporn',
               'Invitation IUMRS-ICEM2026_Symp9_Chair_Ittipon Fongkaew',
              'Invitation IUMRS-ICEM2026_Symp9_Co-chair_Wiwat Nuansing',
         'Invitation IUMRS-ICEM2026_Symp10_Chair_Sirithan Jiemsirilers',
         'Invitation IUMRS-ICEM2026_Symp10_Co-chair_Pakorn Opaprakasit',
         'Invitation IUMRS-ICEM2026_Symp10_Co-chair_Oratai Jongprateep',
            'Invitation IUMRS-ICEM2026_Symp10_Co-chair_Niti Yongvanich',
             'Invitation IUMRS-ICEM2026_Symp11_Chair_Worawat Meevasana',
      'Invitation IUMRS-ICEM2026_Symp11_Co-chair_Anucha Watcharapasorn',
        'Invitation IUMRS-ICEM2026_Symp11_Co-chair_Sukrit Sucharitakul',
     'Invitation IUMRS-ICEM2026_Symp11_Co-chair_Nithiwadee Thaicharoen',
     'Invitation IUMRS-ICEM2026_Symp11_Co-chair_Phatthamon Kongkhambut',
            'Invitation IUMRS-ICEM2026_Symp12_Chair_Anchalee Manonukul',
       'Invitation IUMRS-ICEM2026_Symp12_Co-chair_Hathaikarn Manuspiya',
      'Invitation IUMRS-ICEM2026_Symp12_Co-chair_Sirithan Jiemsirilers',
            'Invitation IUMRS-ICEM2026_Symp13_Chair_Jakrapong Kaewkhao',
        'Invitation IUMRS-ICEM2026_Symp13_Co-chair_Naratip Vittayakorn',
             'Invitation IUMRS-ICEM2026_Symp13_Co-chair_Suchart Kothan',
        'Invitation IUMRS-ICEM2026_Symp13_Co-chair_Patarawagee  Yasaka',
             'Invitation IUMRS-ICEM2026_Symp13_Co-chair_Narit Triamnak',
      'Invitation IUMRS-ICEM2026_Symp13_Co-chair_Wutthikrai Busayaporn',
     'Invitation IUMRS-ICEM2026_Symp13_Co-chair_Phakkhananan Pakawanit',
           'Invitation IUMRS-ICEM2026_Symp13_Co-chair_Phieraya Pulphol']
Length: 54, dtype: str

In [8]:
df["docx"] = df["filename"] + ".docx"
df["pdf"] = df["filename"] + ".pdf"

In [9]:
df.columns

Index(['Num', 'Symposia', 'Role', 'Thai', 'Name', 'Affiliation', 'Email',
       'Ignore', 'name_strip', 'title', 'filename', 'docx', 'pdf'],
      dtype='str')

In [10]:
df.to_excel("output_excel/S01_data.xlsx", index=False)